runtime: nodejs12

instance_class: F2
automatic_scaling:
  max_instances: 2

handlers:
  - url: /
    script: auto
    redirect_http_response_code: 301
    secure: always

  - url: /(.*)
    static_files: dist/\1
    upload: dist/(.*)
    secure: always
# https://mda-covid-19.appspot.com/
# gcloud app deploy app.yaml --project=mda-covid-19 --version=2020-12-04
